### ISSUE TITLE
# Database Schema

### ISSUE THREAD

**Issue by andy-h-2016** [internetmara/FullStack#3]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by andy-h-2016** [comment]
- **cart**
  - I know we called it `cart` in our discussion yesterday, but looking at the schema now, I think `orders` would be a more descriptive table name.
  - If you want to be able to "purchase" products and see your past orders, then you can create a column to log a unique identifier for each batch of "purchased" orders (like a timestamp or randomized string) at the time of purchase. Orders that do not have this identifier (i.e. have a `null` value) would be the items in a user's cart.
  - there should be a `quantity` column to signify how much a user is ordering of a specific product.
- **products**
  - `quantity` should be dropped. 
    - If `quantity` refers to how much someone is ordering, then that should go under `cart`/`orders`
    - If `quantity` refers to how much a dispensary has, you probably won't be displaying that info on the webpage, so you can just get rid of this column and worry about one less thing.
  - `dispensary_id` should be unique with respect to `name`; a dispensary should not have 2 products with the same name.

**Comment by internetmara** [comment]
So quantity actually theoretically refers to a lot of things. Maybe "amount" or "size" would be better? For example, you can purchase an 8th or a quarter or an oz all of the same strain if it's flower. Cartridges come in .5 grams or 1 gram... there's also like different concentrations of processed products. Edibles can come in different sized packages even if it's the same product in every other sense... plus then there's like the number of each unit you decide to get. 

Idk... thoughts? I suppose that could also go in the cart but it's kinda like the number of units vs unit size if that makes sense. 

As far as the naming thing goes, it's kind of the same deal. There's like "Northern Lights" for example and it comes in different amounts but would otherwise be the exact same brand, strain, etc... maybe just different prices? You can also have the same strain name in the same size but from different brands... I'm just not sure the best way to handle that for organizational purposes. It's not uncommon for there to be multiple products with the same name...

**Comment by andy-h-2016** [comment]
Hm, alright. That does make sense to have a separate quantities for both `products` and `orders` then. I think one of them should be name something different to make it less confusing though.

Did not consider that you could have Northern Lights small, medium, large, etc. One idea is that you could put the size/quantity in the name so that you have one less column to keep track of. Otherwise you can forget about the name/dispensary unique constraint. 

Only concern with having a size/quantity column are the varying units of measurement, which would make it difficult to sort them. You'll have to decide if you want that column to be a string that includes the UoM or if you will make them all the same UoM. That's a minor concern though, I wouldn't stay up late thinking about that one.

**Comment by andy-h-2016** [comment]
Closing this issue, but you can still change your schema if need be.
